### ISSUE TITLE
All elements of SensorState need documentation of units

### ISSUE THREAD

**Issue by tfoote** [yujinrobot/kobuki_msgs#1]
Most are currently not documented.   They can just be comments in the message, and if possible they should follow REP 103 http://www.ros.org/reps/rep-0103.html

**Comment by bit-pirate** [comment]
OK, I'll grab Einstein an fill in the missing information.

**Comment by bit-pirate** [comment]
Looks solved for me. Create new issues, if something is missing or unclear.
