### ISSUE TITLE
CliffEvent has flipped position for sensor and state

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/kobuki_msgs#4]
when compared to the other events, e.g. bumper, wheel drop.
This confuses when checking the topic output on comandline.

http://ros.org/doc/api/kobuki_msgs/html/msg/CliffEvent.html

**Comment by stonier** [comment]
Just looked at the bumper event, can't work out what you mean by 'flipper position'.

**Comment by bit-pirate** [comment]
Sorry, misspelled it. I meant "flipped" and by that I mean that usually we have

```
state
wheel (or bumper)
```

But in the CliffEvent it's

```
sensor
state
```

So, at the first look state and sensor is easily misinterpreted.

**Comment by corot** [comment]
he he...  I realized and fixed this yesterday when I added extra comments to the headers.

19969252e04d2f73b57833802a4fb571d83585b5
